#ifndef CLOCK_H
#define CLOCK_H

/* TI manual section 8.1.12.2*/

#define PRCM_BASE 0x44E00000

#define CM_WKUP_BASE 0x44E00400

/* CORE PLL */
#define CM_CLKMODE_DPLL_CORE (CM_WKUP_BASE + 0x90)
#define CM_IDLEST_DPLL_CORE  (CM_WKUP_BASE + 0x5C) 
#define CM_CLKSEL_DPLL_CORE (CM_WKUP_BASE + 0x68)

#define CM_DIV_M4_DPLL_CORE (CM_WKUP_BASE + 0x80)
#define CM_DIV_M5_DPLL_CORE (CM_WKUP_BASE + 0x84)
#define CM_DIV_M6_DPLL_CORE (CM_WKUP_BASE + 0xD8)

/* PERIPHERAL PLL */

#define CM_CLKMODE_DPLL_PER (CM_WKUP_BASE + 0x8C)
#define CM_IDLEST_DPLL_PER (CM_WKUP_BASE + 0x70)
#define CM_CLKSEL_DPLL_PER (CM_WKUP_BASE + 0x9C)

#define CM_DIV_M2_DPLL_PER (CM_WKUP_BASE + 0xAC)

#define CM_EMIF_FW_CLKCTRL (PRCM_BASE + 0xD0)
#define CM_EMIF_CLKCTRL (PRCM_BASE + 0x28)
#define CM_PER_L3_CLKCTRL (PRCM_BASE + 0xC)


/* MPU PLL */

#define CM_CLKMODE_DPLL_MPU (CM_WKUP_BASE + 0x88)
#define CM_IDLEST_DPLL_MPU (CM_WKUP_BASE + 0x20)
#define CM_CLKSEL_DPLL_MPU (CM_WKUP_BASE + 0x2C)

#define CM_DIV_M2_DPLL_MPU (CM_WKUP_BASE + 0xA8)

/* DDR PLL */
#define CM_CLKMODE_DPLL_DDR (CM_WKUP_BASE + 0x94)
#define CM_IDLEST_DPLL_DDR (CM_WKUP_BASE + 0x34)
#define CM_CLKSEL_DPLL_DDR (CM_WKUP_BASE + 0x40)

#define CM_DIV_M2_DPLL_DDR (CM_WKUP_BASE + 0xA0)

void initClocks();

#endif
